package com.example.greendaodemo;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.greendaodemo.Person;
import com.example.greendaodemo.Animal;

import com.example.greendaodemo.PersonDao;
import com.example.greendaodemo.AnimalDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personDaoConfig;
    private final DaoConfig animalDaoConfig;

    private final PersonDao personDao;
    private final AnimalDao animalDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        animalDaoConfig = daoConfigMap.get(AnimalDao.class).clone();
        animalDaoConfig.initIdentityScope(type);

        personDao = new PersonDao(personDaoConfig, this);
        animalDao = new AnimalDao(animalDaoConfig, this);

        registerDao(Person.class, personDao);
        registerDao(Animal.class, animalDao);
    }
    
    public void clear() {
        personDaoConfig.clearIdentityScope();
        animalDaoConfig.clearIdentityScope();
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public AnimalDao getAnimalDao() {
        return animalDao;
    }

}
